Repository Icinga/icingaweb2-module-graphite, pull requests merged in 2022-03, with the labels that each got.

#264 Disable autorefreshes while timerange picker is open
  library/Graphite/Web/Controller/TimeRangePickerTrait.php
Labels: bug, cla/signed

#266 04-Templates.md: Add note for required sections of template file
  doc/04-Templates.md
Labels: cla/signed

#259 Add icingadb support
  application/controllers/GraphController.php
  application/controllers/HostsController.php
  application/controllers/ListController.php
  application/controllers/ServicesController.php
  configuration.php
  library/Graphite/Graphing/MetricsQuery.php
  library/Graphite/Graphing/Template.php
  library/Graphite/ProvidedHook/Icingadb/HostDetailExtension.php
  library/Graphite/ProvidedHook/Icingadb/IcingadbSupport.php
  library/Graphite/ProvidedHook/Icingadb/ServiceDetailExtension.php
  library/Graphite/ProvidedHook/Monitoring/DetailviewExtension.php
  library/Graphite/Web/Controller/IcingadbGraphiteController.php
  library/Graphite/Web/Controller/MonitoringAwareController.php
  library/Graphite/Web/Widget/Graphs.php
  library/Graphite/Web/Widget/Graphs/Host.php
  library/Graphite/Web/Widget/Graphs/Icingadb/IcingadbHost.php
  library/Graphite/Web/Widget/Graphs/Icingadb/IcingadbService.php
  library/Graphite/Web/Widget/Graphs/Service.php
  library/Graphite/Web/Widget/IcingadbGraphs.php
  module.info
  public/css/module.less
  run.php
Labels: enhancement, cla/signed

#270 Fix/make traits initialised by class
  application/controllers/GraphController.php
  library/Graphite/Graphing/MetricsQuery.php
  library/Graphite/Util/IcingadbUtils.php
Labels: bug, cla/signed

#272 Add `setAutoRefresh(30)` to `Hosts|ServicesController`
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
Labels: cla/signed

#271 Remove superfluous call to `$this->applyRestrictions()`
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
Labels: cla/signed

#268 Add doc for special chars
  doc/05-Troubleshooting.md
Labels: enhancement, area/documentation, cla/signed

#267 Make graphite path wildcards work
  doc/04-Templates.md
  library/Graphite/Graphing/GraphiteWebClient.php
  library/Graphite/Graphing/MetricsQuery.php
  library/Graphite/Util/MacroTemplate.php
  library/Graphite/Web/Widget/GraphImage.php
Labels: enhancement, area/templates, cla/signed

#246 ethMon template
  templates/ethMon.ini
Labels: enhancement, area/templates
