Repository Icinga/icingaweb2-module-graphite, pull requests merged in 2025-01, with the labels that each got.

#334 Fix broken link
  doc/04-Templates.md
Labels: cla/signed

#327 Template: Fix multi template graphs
  library/Graphite/Graphing/Template.php
Labels: bug, cla/signed

#324 Update templates for Icinga Powershell plugins
  templates/cpu_windows_powershell_framework.ini
  templates/disk_windows_powershell_framework.ini
  templates/memory_windows_powershell_framework.ini
Labels: bug, cla/signed

#335 Templates: Set `yUnitSystem` to `msec`
  templates/hostalive.ini
  templates/icmp.ini
  templates/ping.ini
Labels: enhancement, cla/signed
